name: Build Next.js web application
on: push
  jobs:
  name: Build container
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Push to Docker Hub
    uses: docker/build-push-action@v1
    with:
      username: ${{ secrets.DOCKER_USER }}
      password: ${{ secrets.DOCKER_PW }}
      repository: yuduu/SmartDisplay
      tags: latest, ${{ github.run_number }}