name: Build SmartDisplay web application
on: 
  push:
    branches:
      - 'main'

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PW }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64, linux/arm/v7
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: yuduu/smartdisplay:latest